{% set version = "0.6.0.84" %}

package:
  name: cublasmp
  version: {{ version.split('.')[:3] | join('.') }}

source:
  url: https://developer.download.nvidia.com/compute/cublasmp/redist/libcublasmp/LICENSE.txt
  sha256: c2a95a3d181879325e56333d7a592bb6ba5ab3a44bfde9574513ccc2f87f9c68

build:
  number: 0
  noarch: generic

requirements:
  run:
    - libcublasmp-dev {{ version }}

test:
  commands:
    - exit 0

about:
  home: https://docs.nvidia.com/cuda/cublasmp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE.txt
  license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
  summary: Meta-package containing all NVIDIA cuBLASMp packages, not intended for use in a conda-build context.
  description: |
    NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
    cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
  doc_url: https://docs.nvidia.com/cuda/cublasmp/

extra:
  recipe-maintainers:
    - almogsegal
    - mrogowski
    - conda-forge/cuda
