{% set version = "0.4.0" %}

package:
  name: cublasmp
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cublasmp/redist/libcublasmp/LICENSE.txt
  sha256: c2a95a3d181879325e56333d7a592bb6ba5ab3a44bfde9574513ccc2f87f9c68

build:
  number: 1
  noarch: generic

requirements:
  run:
    - libcal-dev 0.4.4.50
    - libcublasmp-dev 0.4.0.789

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all NVIDIA cublasMp packages, not intended for use in a conda-build context.
  description: |
    NVIDIA cublasMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
    cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
    A companion library, CAL, contains utilities to manage communicators and to synchronize processes in a safe way.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - almogsegal
    - mrogowski
    - conda-forge/cuda
